
[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_flags = 
  -DREFINANCE_D1_MINI=1
  -DAPI_INSECURE_TLS=1
lib_deps = 
  adafruit/Adafruit PN532 @ ^1.3.0
  marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
  bblanchon/ArduinoJson @ ^7.0.4

[env:native]
platform = native
build_flags = 
  -DUNIT_TEST
